/*Componentes IU */
export { default as Accordionn } from "./ui/Accordionn";
export { default as Checkbox } from "./ui/Checkbox";
export { default as Input } from "./ui/Input";
export { default as Label } from "./ui/Label";
export { default as Label2 } from "./ui/Label2";
export { default as Select } from "./ui/Select";
export { default as BenefitsCurrent } from "./ui/BenefitsCurrent";
export { default as Button } from "./ui/Button";
export { default as Card } from "./ui/Card";
export { default as Chart } from "./ui/Chart";
export { default as InfoMembers } from "./ui/InfoMembers";
export { default as Search } from "./ui/search";
export { default as TablaUno } from "./ui/TablaUno";
export { default as TableLine } from "./ui/TableLine";
export { default as TextArea } from "./ui/TextArea";
export { default as Tr } from "./ui/Tr";
export { default as CardIcon } from "./ui/CardIcon";
export { default as Modal } from "./ui/Modal";
export { default as ToggleCheck } from "./ui/ToggleCheck";
export { default as Spinner } from "./ui/Spinner";
export { default as Spinner2 } from "./ui/Spinner2";
export { default as Hr } from "./ui/Hr";
export { default as Payment } from "./ui/Payment";
export { default as Flex } from "./ui/Flex";
export { default as LiTab } from "./ui/LiTab";
export { default as Saved } from "./modal-saving/Saved";
export { default as Navigation } from "./main-menu/MainMenu";
export { default as SimpleTable } from "./ui/SimpleTable";
export { default as Header } from "./ui/Header";
export { default as Note } from "./ui/Note";
export { default as CustomerData } from "./ui/CustomerData";
export { default as TreeView } from "./reports/report-editor-home/TreeView";
export { default as CustomerResult } from "./ui/CustomerResult";
export { default as RadioButon } from "./ui/RadioButon";
export { default as ModalReactstrap } from "./ui/ModalReactstrap";
export { default as Log } from "./ui/Log";
export { default as LogDetail } from "./ui/LogDetail";
export { default as MenuButton } from "./ui/MenuButton"

/*Vistas */
export { default as AddMember } from './add-member/AddMember'
export { default as AddProvision } from './new-partner/W3-AddProvision'
export { default as Panel } from './main-panel/Panel'
export { default as SaleCapture } from './sale-capture/SaleCapture'
export { default as AddNote } from './modal-add-note/AddNote'
export { default as MemebershipReport } from './reports/MembershipReport'
export { default as VatRateCoOwner } from './vat-rate-coOwner/VatRateCoOwner'
export { default as VatRate } from './vat-rate/Vat-Rate'
export { default as VatRateNew } from './vat-rate/VatRateNew'
export { default as NewSocioProcessing } from './new-socio-processing/NewSocioProcessing'
export { default as NewPartnerFive } from './add-member/new-partner-five/NewPartnerFive'
export { default as NewPartnerThree } from './add-member/new-partner-three/NewPartnerThree'
export { default as Login } from './login/login'
export { default as Loading } from './loading/Loading'
export { default as NewCreditCard } from './new-credit-card/NewCreditCard'
export { default as GuestInformation } from './guest-information/GuestInformation'
export { default as AddEditPostForm } from "./report-editor/AddEditPostForm"
export { default as EditorComponent } from "./report-editor/EditorComponent"
export { default as MemberResume } from "./members-resume/MembersResume"
export { default as NewSocioPromisses } from './nuevo-socio-promisses/NuevoSocioPromisses'
export { default as MemberInquiry } from "./member-inquiry/MemberInquiry"
export { default as AffiliationUtilities } from "./reports-mr/AffilitationUtilities"
export { default as MemberReportsFor } from "./member-reports-for/MemberReportsFor"
export { default as CustomerSearch } from "./custome-search/CustomerSearch"
export { default as GuestInformationDates } from "./membership-input/GuestInformationDates"
export { default as PackageAcces } from './add-member/w4/PackageAcces'
export { default as QuantyProvisions } from './quantity-provisions/QuantityProvisons'
export { default as CoOwner } from './coOwner/CoOwner'
export { default as Beneficiaries } from './beneficiaries/Beneficiaries'
export { default as OriginInformation } from './origin/OriginInformation'
export { default as Company } from './nuevo-socio-promisses/Company'
export { default as AccDet } from './nuevo-socio-promisses/AccDet'
export { default as Blance } from './nuevo-socio-promisses/Blance'
export { default as GetExistingF } from './nuevo-socio-promisses/GetExistingF'
export { default as Promises } from './member-inquiry/Promises'
export { default as TablePromotions } from './benefits/TablePromotions'
export { default as Certificates } from './benefits/Certificates'
export { default as RefProgram } from './benefits/ReferralProgram'
export { default as ProvisionsBenefits } from './provisions/Provisions'
export { default as NewProvision } from '../views/New-Member/NewProvision'
export { default as Notification } from './ui/Notification'
export { default as BeneficiariesModal } from './beneficiaries-modal/BeneficiariesModal'
export { default as AddresInvoicing } from './invoicing-info/AddressInvoicing'
export { default as InvoicingInfo } from './invoicing-info/InvoicingInfo'
export { default as Cancellationlog } from './additional-information/Cancellationlog'
export { default as CellPhone } from './cell-phone/CellPhone'
export { default as ElectronicWallet } from './electronic-wallet/ElectronicWallet'
export { default as SpaMoney } from './spa-money/SpaMoney'
export { default as CreditCard } from './sale-capture/modules/CreditCard'
export { default as PersonalInformation } from './personal-information/PersonalInformation'
export { default as AffiliationInformation } from './personal-information/AffiliationInformation'
export { default as NewDeposit } from './new-deposit/NewDeposit'
export { default as NotesMenu } from './notes-menu/NotesMenu'
export { default as ReleaseElectronicPurseProducts } from './release-electronicpurse/ReleaseElectronicPurseProducts'
export { default as ReportsMember } from './reports-member/ReportsMember'
export { default as DespositsMaintenance } from './deposits-maintenance/DespositsMaintenance'
export { default as PalaceEliteGolf } from './palace-elite-golf/PalaceEliteGolf'
export { default as MemberProfilesRelated } from './member-profiles-related/MemberProfilesRelated'
export { default as ACHPayment } from './ach-payment/ACHPayment'
export { default as InfoMembersNoContainer } from './info-members/InfoMembersNoContainer'
export { default as AddressMemberByCreditCard } from './members/AddressMemberByCreditCard'
export { default as MemberReservationRates } from './members/MemberReservationRates'
export { default as ModalAffiliationInquery } from './affiliation/ModalAffiliationInquery'
export { default as AdjustMovements } from './ajust-movements/AdjustMovements'
export { default as ManagementReports } from './management-reports/ManagementReports'
export { default as ReportRaffleWeek } from './report-raffle-week/ReportRaffleWeek'
export { default as EInvoicingProcess } from './e-invoicingprocess/EInvoicingProcess'
export { default as InterfazAfilicianes } from './interfaz-afiliciones/InterfazAfilicianes'
export { default as BitacoraSmart } from './bitacora-smart/BitacoraSmart'
export { default as ChangeTransactionItem } from './change-transaction/ChangeTransactionItem'
export { default as CleanSuspense } from './clean-suspense/CleanSuspense'
export { default as EInvoiceCancellation } from './e-invoice-cancellation/EInvoiceCancellation'
export { default as EInvoicing } from './e-invoicing/EInvoicing'
export { default as FrmNotAccounting } from './frm-not-accounting/FrmNotAccounting'
export { default as BenefitPolicyLog } from './frm-not-accounting/BenefitPolicyLog'
export { default as ConfigurationPortfolioBA } from './configuration-portfolio-ba/ConfigurationPortfolioBA'
export { default as MemberDiscountProducts } from './guestInformationTable/MemberDiscountProducts'
export { default as Jobs } from './salesmen/Jobs'
export { default as SalesMen } from './salesmen/SalesMen'
export { default as MemberSalesmenLog } from './salesmen/MemberSalesmenLog'
export { default as MemberSalesmenLogDetail } from './salesmen/MemberSalesmenLogDetail'
export { default as MemberLog } from './salesmen/MemberLog'
export { default as MemberLogDetail } from './salesmen/MemberLogDetail'
export { default as EInvoicingAffilation } from './e-InvoicingAffiliation/EInvoicingAffilation'
export { default as SapAccountingLog } from './accounting-accounts/SapAccountingLog'
export { default as AccountBank } from './account-bank/AccountBank'
export { default as AccountBankDetail } from './account-bank/AccountBankDetail'
export { default as Bank } from './account-bank/Bank'
export { default as BankDetail } from './account-bank/BankDetail'
export { default as PaymentPosting } from './paymentPosting/PaymentPosting'
export { default as ReportUniversalCredit } from './reports/ReportUniversalCredit'
export { default as ReportCycleMonthlyDeling } from './reports/ReportCycleMonthlyDeling'
export { default as AccountStatement } from './reports/AccountStatement'
export { default as ConcordNotes } from './concord-notes/ConcordNotes'
export { default as MemberProvisionSL } from './member-provision-status-log/MemberProvisionSL'
export { default as SaleDetail } from './sale-capture/modules/SaleDetail'
export { default as FinancingDetail } from './sale-capture/modules/FinancingDetail'
export { default as StayDetail } from './sale-capture/modules/StayDetail'
export { default as ListOfBenefits } from './listof-benefits/ListOfBenefits'
export { default as RequerimentoAutorizaciones } from './requerimento-autorizaciones/RequerimentoAutorizaciones'
export { default as TypeBenefitRules } from './type-benefitrules/TypeBenefitRules'
export { default as TagManagement } from './tag-management/TagManagement'
export { default as TagDetail } from './tag-detail/TagDetail'
export { default as ManagementBenefit } from './management-benefit/ManagementBenefit'
export { default as CreateBenefitType } from './management-benefit/CreateBenefitType'
export { default as CreateBenefit } from './management-benefit/CreateBenefit'
export { default as DetailsJob } from './job/DetailsJob'
export { default as Hotels } from './hotels/Hotels'
export { default as DetailsHotel } from './hotels/DetailsHotel'
export { default as DetailsRoomTypeAccess } from './room-type-access/DetailsRoomTypeAccess'
export { default as GeneralTA } from './room-type-access/GeneralTA'
export { default as ClausesTA } from './room-type-access/ClausesTA'
export { default as CallCenterTA } from './room-type-access/CallCenterTA'
export { default as PromotionBenefitDetail } from './promotion/PromotionBenefitDetail'
export { default as PromotionSpecificationDetail } from './promotion/PromotionSpecificationDetail'
export { default as ProvisionBenefitDetail } from './promotion/ProvisionBenefitDetail'
export { default as Provision } from './provision/Provision'
export { default as ElectronicPurseProduct } from './release-electronicpurse/ElectronicPurseProduct'
export { default as DiscountProducts } from './discount-products/DiscountProducts'
export { default as UpdateMasterFile } from './update-master-file/UpdateMasterFile'
export { default as Process } from './update-master-file/Process'
export { default as Pending } from './update-master-file/Pending'
export { default as Errors } from './update-master-file/Errors'
export { default as AdditionalFeesImperialWeeks } from './additionalfees-imperialweeks/AdditionalFeesImperialWeeks'
export { default as ImperialWeekRate } from './additionalfees-imperialweeks/ImperialWeekRate'
export { default as AdditionalFeesImperialLog } from './additionalfees-imperialweeks/AdditionalFeesImperialLog'
export { default as AdditionalFeesImperialLogDetail } from './additionalfees-imperialweeks/AdditionalFeesImperialLogDetail'
export { default as DiamontClassification } from './diamond-classification/DiamontClassification'
export { default as DiamontClassificationDetail } from './diamond-classification/DiamontClassificationDetail'
export { default as DiamontClassificationLog } from './diamond-classification/DiamontClassificationLog'
export { default as DiamontClassificationLogDetail } from './diamond-classification/DiamontClassificationLogDetail'
export { default as AsmCatalogs } from './catalogs-asm/AsmCatalogs'
export { default as AsmCatalogsDetail } from './catalogs-asm/AsmCatalogsDetail'
export { default as AsmCatalogsLog } from './catalogs-asm/AsmCatalogsLog'
export { default as AsmCatalogsLogDetail } from './catalogs-asm/AsmCatalogsLogDetail'
export { default as HotelsOutHouse } from './hotels-out-house/HotelsOutHouse'
export { default as HotelsOutHouseDetail } from './hotels-out-house/HotelsOutHouseDetail'
export { default as HotelsOutHouseLog } from './hotels-out-house/HotelsOutHouseLog'
export { default as HotelsOutHouseLogDetail } from './hotels-out-house/HotelsOutHouseLogDetail'
export { default as Nationalities } from './nationalities/Nationalities'
export { default as NationalitiesDetail } from './nationalities/NationalitiesDetail'
export { default as NationalitiesLog } from './nationalities/NationalitiesLog'
export { default as NationalitiesLogDetail } from './nationalities/NationalitiesLogDetail'
export { default as AccessHotels } from './access-hotels/AccessHotels'
export { default as DetailAccessHotels } from './access-hotels/DetailAccessHotels'
export { default as AccessHotelLog } from './access-hotels/AccessHotelLog'
export { default as AccessHotelLogDetail } from './access-hotels/AccessHotelLogDetail'
export { default as DemographicAreas } from './demographic-areas/DemographicAreas'
export { default as DemographicAreaEditing } from './demographic-areas/DemographicAreaEditing'
export { default as PortafolioCompanies } from './portafolio-companies/PortafolioCompanies'
export { default as PortafolioCompany } from './portafolio-companies/PortafolioCompany'
export { default as TableGestId } from './membership-input/TableGestId'
export { default as GolfRateDetail } from './golf-rates-discount/GolfRateDetail'
export { default as GolfRatesDiscount } from './golf-rates-discount/GolfRatesDiscount'
export { default as GolfRatesDiscountLog } from './golf-rates-discount/GolfRatesDiscountLog'
export { default as GolfRatesLogDetail } from './golf-rates-discount/GolfRatesLogDetail'
export { default as OfficeEditing } from './offices/OfficeEditing'
export { default as OfficeLogDetail } from './offices/OfficeLogDetail'
export { default as Offices } from './offices/Offices'
export { default as OfficesLog } from './offices/OfficesLog'
export { default as PlanDetail } from './plans/PlanDetail'
export { default as Plans } from './plans/Plans'
export { default as PlansLog } from './plans/PlansLog'
export { default as PlansLogDetail } from './plans/PlansLogDetail'
export { default as TableWallet } from './benefits/TableWallet'
export {default as AssignmentOfDiamindClassifications} from './assignment/AssignmentOfDiamindClassifications'