export const data = [
    {
        "RECNUM": "27",
        "IDTYPEROOM": "6",
        "DESCRIPTION": "Standard",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "1",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "J",
        "Checkbox": "1",
        "TotAccess": "2",
        "Link": "0"
    },
    {
        "RECNUM": "28",
        "IDTYPEROOM": "7",
        "DESCRIPTION": "Royal de Luxe Le Blanc Cancun",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "2",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RL",
        "Checkbox": "1",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "56",
        "IDTYPEROOM": "36",
        "DESCRIPTION": "Royal de Luxe Le Blanc Cabos",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "34",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLCB",
        "Checkbox": "1",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "72",
        "IDTYPEROOM": "52",
        "DESCRIPTION": "Grand Presidential Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "52",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GSP",
        "Checkbox": "1",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "113",
        "IDTYPEROOM": "94",
        "DESCRIPTION": "Superior Deluxe Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "90",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "SDPC",
        "Checkbox": "1",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "45",
        "IDTYPEROOM": "24",
        "DESCRIPTION": "Luxury Suite Jamaica",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "23",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "LSJ",
        "Checkbox": "1",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "129",
        "IDTYPEROOM": "110",
        "DESCRIPTION": "Junior Suite Campo de Golf MPS",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "JSCG",
        "Checkbox": "1",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "130",
        "IDTYPEROOM": "111",
        "DESCRIPTION": "Governor Sun Palace",
        "STATUS": "A",
        "AGRUPADOR": "G",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "G",
        "CategoryName": "Governor",
        "CategoryOrder": "2",
        "GroupName": "Governor",
        "GroupOrder": "3",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GVSP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "131",
        "IDTYPEROOM": "112",
        "DESCRIPTION": "Presidential Campo de Golf VIP Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PG",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "132",
        "IDTYPEROOM": "113",
        "DESCRIPTION": "Presidential (Two bedrooms) Le Blanc Cancun Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PL",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "133",
        "IDTYPEROOM": "114",
        "DESCRIPTION": "Lock off Presidential Beach Palace Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "LOPBP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "134",
        "IDTYPEROOM": "115",
        "DESCRIPTION": "Lock Off Presidential Sun Palace Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "LOPSP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "135",
        "IDTYPEROOM": "116",
        "DESCRIPTION": "Lock Off Grand Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GLOCK",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "136",
        "IDTYPEROOM": "117",
        "DESCRIPTION": "Lock Off Presidencial Beach Palace Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "LOPBP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "137",
        "IDTYPEROOM": "118",
        "DESCRIPTION": "Lock Off Presidential Sun Palace Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "LOPSP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "138",
        "IDTYPEROOM": "119",
        "DESCRIPTION": "Lock Off Baby Residence Three Bedrooms Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "73",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RLO3BPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "139",
        "IDTYPEROOM": "120",
        "DESCRIPTION": "Lock Off Baby Residence Two Bedrooms Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "74",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RLO2BPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "140",
        "IDTYPEROOM": "121",
        "DESCRIPTION": "Lock Off Residence Two Bedrooms Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "75",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLO2BPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "141",
        "IDTYPEROOM": "122",
        "DESCRIPTION": "Lock Off Residence Three Bedrooms Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "75",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLO3BPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "46",
        "IDTYPEROOM": "25",
        "DESCRIPTION": "Presidential Platinum Jamaica",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "25",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PJ",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "47",
        "IDTYPEROOM": "26",
        "DESCRIPTION": "Family Jamaica ",
        "STATUS": "A",
        "AGRUPADOR": "F",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Family",
        "GroupOrder": "2",
        "PRINTORDER": "30",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "FJ",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "48",
        "IDTYPEROOM": "27",
        "DESCRIPTION": "Governor Jamaica ",
        "STATUS": "A",
        "AGRUPADOR": "G",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "G",
        "CategoryName": "Governor",
        "CategoryOrder": "2",
        "GroupName": "Governor",
        "GroupOrder": "3",
        "PRINTORDER": "32",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GJ",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "49",
        "IDTYPEROOM": "29",
        "DESCRIPTION": "Villa Jamaica (4 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "27",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VJ4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "50",
        "IDTYPEROOM": "30",
        "DESCRIPTION": "Villa Jamaica (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "29",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VJ3",
        "Checkbox": "0",
        "TotAccess": "8",
        "Link": "0"
    },
    {
        "RECNUM": "51",
        "IDTYPEROOM": "31",
        "DESCRIPTION": "Presidential Silver Jamaica",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "26",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PJ",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "52",
        "IDTYPEROOM": "32",
        "DESCRIPTION": "Baby Villa Jamaica (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "21",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VJ3",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "53",
        "IDTYPEROOM": "33",
        "DESCRIPTION": "Baby Villa Jamaica (4 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "31",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VJ4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "54",
        "IDTYPEROOM": "34",
        "DESCRIPTION": "Lock Off Presidential Le Blanc Cancun Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "15",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PL1BR",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "55",
        "IDTYPEROOM": "35",
        "DESCRIPTION": "Lock Off Presidential Le Blanc Cabos Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "33",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PLCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "114",
        "IDTYPEROOM": "95",
        "DESCRIPTION": "Presidential Platinum Punta Cana ",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "91",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "115",
        "IDTYPEROOM": "96",
        "DESCRIPTION": "Baby Villa Punta Cana  (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "92",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VPC3",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "116",
        "IDTYPEROOM": "97",
        "DESCRIPTION": "Baby Villa Punta Cana (4 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "93",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VPC4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "117",
        "IDTYPEROOM": "98",
        "DESCRIPTION": "Villa Punta Cana (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "94",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VPC3",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "118",
        "IDTYPEROOM": "99",
        "DESCRIPTION": "Villa Punta Cana (4 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "95",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VPC4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "119",
        "IDTYPEROOM": "100",
        "DESCRIPTION": "Baby Residence Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "96",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "120",
        "IDTYPEROOM": "101",
        "DESCRIPTION": "Residence Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "96",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "121",
        "IDTYPEROOM": "102",
        "DESCRIPTION": "Superior Deluxe Punta Cana Trial / Exit ",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "3",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "97",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "SDPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "122",
        "IDTYPEROOM": "103",
        "DESCRIPTION": "Presidential Platinum Punta Cana Trial/Exit",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "3",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "98",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "123",
        "IDTYPEROOM": "104",
        "DESCRIPTION": "Presidential Silver Punta Cana",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "124",
        "IDTYPEROOM": "105",
        "DESCRIPTION": "Presidential Silver Punta Cana Trial/Exit",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "3",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "125",
        "IDTYPEROOM": "106",
        "DESCRIPTION": "Villa Cozumel (2 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VC2B",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "126",
        "IDTYPEROOM": "107",
        "DESCRIPTION": "Baby Villa Cozumel (2 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "99",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VC2B",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "127",
        "IDTYPEROOM": "108",
        "DESCRIPTION": "Lock Off Villa Cozumel ",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "97",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VLC2B",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "128",
        "IDTYPEROOM": "109",
        "DESCRIPTION": "Lock Off Baby Villa  Cozumel",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "98",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VLC2B",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "22",
        "IDTYPEROOM": "1",
        "DESCRIPTION": "Presidential",
        "STATUS": "B",
        "AGRUPADOR": "NULL",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "8",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "23",
        "IDTYPEROOM": "2",
        "DESCRIPTION": "Presidential Platinum BP,SP,MPS,PL,CZ",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "17",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "24",
        "IDTYPEROOM": "3",
        "DESCRIPTION": "Presidential (Two bedrooms) Le Blanc Cancun Platin",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "14",
        "BOLD": "1",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PL",
        "Checkbox": "0",
        "TotAccess": "10",
        "Link": "0"
    },
    {
        "RECNUM": "25",
        "IDTYPEROOM": "4",
        "DESCRIPTION": "Governor Le Blanc Cancun",
        "STATUS": "A",
        "AGRUPADOR": "G",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "G",
        "CategoryName": "Governor",
        "CategoryOrder": "2",
        "GroupName": "Governor",
        "GroupOrder": "3",
        "PRINTORDER": "9",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GL",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "26",
        "IDTYPEROOM": "5",
        "DESCRIPTION": "Governor Playacar",
        "STATUS": "A",
        "AGRUPADOR": "G",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "G",
        "CategoryName": "Governor",
        "CategoryOrder": "2",
        "GroupName": "Governor",
        "GroupOrder": "3",
        "PRINTORDER": "11",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "73",
        "IDTYPEROOM": "53",
        "DESCRIPTION": "Grand Presidential Silver - Low Season",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "53",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "74",
        "IDTYPEROOM": "54",
        "DESCRIPTION": "Residence Le Blanc Cabos",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "54",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RECB",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "75",
        "IDTYPEROOM": "55",
        "DESCRIPTION": "Junior Suite Jamaica",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "24",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "JSJAM",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "76",
        "IDTYPEROOM": "56",
        "DESCRIPTION": "Junior Suite Le Blanc Cancun",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "4",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "JSLBC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "78",
        "IDTYPEROOM": "58",
        "DESCRIPTION": "Residence Nizuc",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "55",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RE",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "79",
        "IDTYPEROOM": "59",
        "DESCRIPTION": "Grand Aqua Presidential Couples oriented Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "49",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GAPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "80",
        "IDTYPEROOM": "60",
        "DESCRIPTION": "Grand Aqua Presidential Families oriented Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "48",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GAPF",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "81",
        "IDTYPEROOM": "61",
        "DESCRIPTION": "Grand Aqua Presidential Couples oriented Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "56",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GAPC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "82",
        "IDTYPEROOM": "62",
        "DESCRIPTION": "Grand Aqua Presidential Families oriented Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "57",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GAPF",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "83",
        "IDTYPEROOM": "63",
        "DESCRIPTION": "Governor Le Blanc Cabos",
        "STATUS": "A",
        "AGRUPADOR": "G",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "G",
        "CategoryName": "Governor",
        "CategoryOrder": "2",
        "GroupName": "Governor",
        "GroupOrder": "3",
        "PRINTORDER": "58",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "84",
        "IDTYPEROOM": "64",
        "DESCRIPTION": "Honeymoon Suite Le Blanc Cancun",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "61",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "HS",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "85",
        "IDTYPEROOM": "65",
        "DESCRIPTION": "Villa Le Blanc Cabos (4 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "59",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VCB4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "86",
        "IDTYPEROOM": "67",
        "DESCRIPTION": "Baby Villa Le Blanc Cabos (4 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "60",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VCB4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "87",
        "IDTYPEROOM": "68",
        "DESCRIPTION": "Baby Residence Le Blanc Cabos",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "61",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RECB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "88",
        "IDTYPEROOM": "69",
        "DESCRIPTION": "Concierge Suite ",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "44",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "CS",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "89",
        "IDTYPEROOM": "70",
        "DESCRIPTION": "Jungle Villa at the Moon Palace Golf Course",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "45",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "JVCG",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "90",
        "IDTYPEROOM": "71",
        "DESCRIPTION": "Baby Jungle Villa at the Moon Palace Golf Course",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "71",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "JVCG",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "91",
        "IDTYPEROOM": "72",
        "DESCRIPTION": "Presidential Diamond Le Blanc Cabos Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "72",
        "BOLD": "1",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PDLCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "92",
        "IDTYPEROOM": "73",
        "DESCRIPTION": "Presidential (Two Bedrooms) Le Blanc Cabos Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "73",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PL2BED",
        "Checkbox": "0",
        "TotAccess": "5",
        "Link": "0"
    },
    {
        "RECNUM": "93",
        "IDTYPEROOM": "74",
        "DESCRIPTION": "Presidential (Two Bedrooms) Le Blanc Cabos Platinu",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "47",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PL2BED",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "94",
        "IDTYPEROOM": "75",
        "DESCRIPTION": "Honeymoon Suite Le Blanc Cabos",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "74",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "HSB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "95",
        "IDTYPEROOM": "76",
        "DESCRIPTION": "Junior Suite Le Blanc Cabos",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "75",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "JSLCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "96",
        "IDTYPEROOM": "77",
        "DESCRIPTION": "Presidential (One Bedroom) Le Blanc Cabos",
        "STATUS": "B",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "76",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "LOLCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "97",
        "IDTYPEROOM": "78",
        "DESCRIPTION": "Presidential Le Blanc Cabos Silver",
        "STATUS": "B",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "58",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PL2BED",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "98",
        "IDTYPEROOM": "79",
        "DESCRIPTION": "Honeymoon Suite Playacar",
        "STATUS": "B",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "77",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "HSPL",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "99",
        "IDTYPEROOM": "80",
        "DESCRIPTION": "Wellness (LB Cancun)",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "S",
        "CategoryName": "Swim Up y Sand",
        "CategoryOrder": "3",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "78",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "WLC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "100",
        "IDTYPEROOM": "81",
        "DESCRIPTION": "Walk out Suite (Sand) Jamaica ",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "S",
        "CategoryName": "Swim Up y Sand",
        "CategoryOrder": "3",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "81",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "WSJ",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "101",
        "IDTYPEROOM": "82",
        "DESCRIPTION": "Lock Off Residence Three Bedrooms Cabos",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "82",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLO3BC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "102",
        "IDTYPEROOM": "83",
        "DESCRIPTION": "Lock Off Residence Three Bedrooms Nizuc ",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "83",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLO3BN",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "103",
        "IDTYPEROOM": "84",
        "DESCRIPTION": "Lock Off ResidenceTwo Bedrooms Cabos",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "84",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLOFC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "104",
        "IDTYPEROOM": "85",
        "DESCRIPTION": "Lock Off Residence Two Bedrooms Nizuc",
        "STATUS": "A",
        "AGRUPADOR": "R",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Residence",
        "GroupOrder": "10",
        "PRINTORDER": "85",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "RLOF",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "105",
        "IDTYPEROOM": "86",
        "DESCRIPTION": "Lock Off Baby Residence Three Bedrooms Le Blanc Ca",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "86",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RLO3BC",
        "Checkbox": "0",
        "TotAccess": "5",
        "Link": "0"
    },
    {
        "RECNUM": "106",
        "IDTYPEROOM": "87",
        "DESCRIPTION": "Lock Off Baby Residence Three Bedrooms Nizuc",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "87",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RLO3BN",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "107",
        "IDTYPEROOM": "88",
        "DESCRIPTION": "Lock Off Baby Residence Two Berdrooms Le Blanc Cab",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "88",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RLOFC",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "108",
        "IDTYPEROOM": "89",
        "DESCRIPTION": "Lock Off Baby Residence Two Berdrooms Nizuc",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "89",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RLOF",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "109",
        "IDTYPEROOM": "90",
        "DESCRIPTION": "Lock Off Presidential Le Blanc Cancun Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "78",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PL1BR",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "110",
        "IDTYPEROOM": "91",
        "DESCRIPTION": "Lock Off Presidential Le Blanc Cabos Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "77",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PLCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "111",
        "IDTYPEROOM": "92",
        "DESCRIPTION": "Grand Presidential Diamond Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "79",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GDPS",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "112",
        "IDTYPEROOM": "93",
        "DESCRIPTION": "Presidential Diamond Le Blanc Cabos Silver",
        "STATUS": "A",
        "AGRUPADOR": "PD",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Diamond",
        "GroupOrder": "5",
        "PRINTORDER": "79",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PDLCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "57",
        "IDTYPEROOM": "37",
        "DESCRIPTION": "Presidential Diamond Sunrise Silver",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "35",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "DP",
        "Checkbox": "0",
        "TotAccess": "3",
        "Link": "0"
    },
    {
        "RECNUM": "58",
        "IDTYPEROOM": "38",
        "DESCRIPTION": "Presidential Silver - Low Season",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "36",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "59",
        "IDTYPEROOM": "39",
        "DESCRIPTION": "Presidential Campo de Golf Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "37",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "PG",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "60",
        "IDTYPEROOM": "40",
        "DESCRIPTION": "Grand Deluxe",
        "STATUS": "A",
        "AGRUPADOR": "S",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Standard",
        "GroupOrder": "1",
        "PRINTORDER": "38",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GDS",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "61",
        "IDTYPEROOM": "41",
        "DESCRIPTION": "Grand Presidential Diamond",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "39",
        "BOLD": "1",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GDPS",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "62",
        "IDTYPEROOM": "42",
        "DESCRIPTION": "Grand Family",
        "STATUS": "A",
        "AGRUPADOR": "F",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Family",
        "GroupOrder": "2",
        "PRINTORDER": "40",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GFS",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "63",
        "IDTYPEROOM": "43",
        "DESCRIPTION": "Grand Swim Up",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "S",
        "CategoryName": "Swim Up y Sand",
        "CategoryOrder": "3",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "41",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GSWUP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "64",
        "IDTYPEROOM": "44",
        "DESCRIPTION": "Lock Off Grand Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "42",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GLOCK",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "65",
        "IDTYPEROOM": "45",
        "DESCRIPTION": "Grand Baby Thematic Villa (3 Bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "43",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GTV3",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "66",
        "IDTYPEROOM": "46",
        "DESCRIPTION": "Grand Baby Thematic Villa (4 Bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "44",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "GTV4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "67",
        "IDTYPEROOM": "47",
        "DESCRIPTION": "Grand Thematic Villa (3 Bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "45",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GTV3",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "68",
        "IDTYPEROOM": "48",
        "DESCRIPTION": "Grand Thematic Villa (4 Bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "46",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GTV4",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "69",
        "IDTYPEROOM": "49",
        "DESCRIPTION": "Grand Presidential Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "47",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "GSP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "70",
        "IDTYPEROOM": "50",
        "DESCRIPTION": "Villa Le Blanc Cabos (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "FORZAR": "N",
        "VALIDITY": "25",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "50",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "71",
        "IDTYPEROOM": "51",
        "DESCRIPTION": "Baby Villa Le Blanc Cabos (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "51",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VCB",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "29",
        "IDTYPEROOM": "8",
        "DESCRIPTION": "Villa Grand",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "VALIDITY": "0",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "19",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VG",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "30",
        "IDTYPEROOM": "9",
        "DESCRIPTION": "Baby Villa Grand",
        "STATUS": "B",
        "AGRUPADOR": "NULL",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "18",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VG",
        "Checkbox": "0",
        "TotAccess": "5",
        "Link": "0"
    },
    {
        "RECNUM": "31",
        "IDTYPEROOM": "10",
        "DESCRIPTION": "Presidential Campo de Golf Ex/Regular",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "FORZAR": "N",
        "VALIDITY": "10",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "13",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "PG",
        "Checkbox": "0",
        "TotAccess": "3",
        "Link": "0"
    },
    {
        "RECNUM": "32",
        "IDTYPEROOM": "11",
        "DESCRIPTION": "Presidential Diamante",
        "STATUS": "B",
        "AGRUPADOR": "P",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "16",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "33",
        "IDTYPEROOM": "13",
        "DESCRIPTION": "Presidential Silver BP,SP,MPS,PL,CZ",
        "STATUS": "A",
        "AGRUPADOR": "PS",
        "VALIDITY": "15",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential Silver",
        "GroupOrder": "7",
        "PRINTORDER": "12",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "1",
        "Link": "0"
    },
    {
        "RECNUM": "34",
        "IDTYPEROOM": "14",
        "DESCRIPTION": "Lock Off",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "L",
        "CategoryName": "Lock Off",
        "CategoryOrder": "7",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "6",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "LO",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "35",
        "IDTYPEROOM": "15",
        "DESCRIPTION": "Mezzanine",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "7",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "M",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "36",
        "IDTYPEROOM": "16",
        "DESCRIPTION": "Swim up MP Sunrise (before Wellness)",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "S",
        "CategoryName": "Swim Up y Sand",
        "CategoryOrder": "3",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "3",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "SU",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "37",
        "IDTYPEROOM": "17",
        "DESCRIPTION": "Walk out Suite (Sand) Playacar",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "S",
        "CategoryName": "Swim Up y Sand",
        "CategoryOrder": "3",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "5",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "S",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "38",
        "IDTYPEROOM": "18",
        "DESCRIPTION": "Governor MPS/MPN  (antes Ambassador)",
        "STATUS": "A",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "8",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "A",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "39",
        "IDTYPEROOM": "19",
        "DESCRIPTION": "Family MPS/BP",
        "STATUS": "A",
        "AGRUPADOR": "F",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "J",
        "CategoryName": "Standard",
        "CategoryOrder": "1",
        "GroupName": "Family",
        "GroupOrder": "2",
        "PRINTORDER": "10",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "F",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "40",
        "IDTYPEROOM": "20",
        "DESCRIPTION": "Baby Residence Nizuc",
        "STATUS": "A",
        "AGRUPADOR": "BR",
        "FORZAR": "N",
        "VALIDITY": "15",
        "Category": "R",
        "CategoryName": "Residence",
        "CategoryOrder": "6",
        "GroupName": "Baby Residence",
        "GroupOrder": "11",
        "PRINTORDER": "20",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "RE",
        "Checkbox": "0",
        "TotAccess": "20",
        "Link": "0"
    },
    {
        "RECNUM": "41",
        "IDTYPEROOM": "21",
        "DESCRIPTION": "Presidential Diamond Sunrise Platinum",
        "STATUS": "A",
        "AGRUPADOR": "P",
        "FORZAR": "Y",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "Presidential",
        "GroupOrder": "4",
        "PRINTORDER": "20",
        "BOLD": "1",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "DP",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "42",
        "IDTYPEROOM": "22",
        "DESCRIPTION": "Villa Nizuc (3 bedrooms)",
        "STATUS": "A",
        "AGRUPADOR": "V",
        "VALIDITY": "0",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Villa",
        "GroupOrder": "8",
        "PRINTORDER": "22",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "VN",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "43",
        "IDTYPEROOM": "23",
        "DESCRIPTION": "Baby Villa Nizuc",
        "STATUS": "A",
        "AGRUPADOR": "BV",
        "VALIDITY": "10",
        "Category": "V",
        "CategoryName": "Villa",
        "CategoryOrder": "5",
        "GroupName": "Baby Villa",
        "GroupOrder": "9",
        "PRINTORDER": "28",
        "BOLD": "0",
        "PERIODTYPE": "T",
        "ROOMTYPE": "VN",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    },
    {
        "RECNUM": "44",
        "IDTYPEROOM": "12",
        "DESCRIPTION": "Presidential Gold",
        "STATUS": "B",
        "AGRUPADOR": "NULL",
        "FORZAR": "N",
        "VALIDITY": "0",
        "Category": "P",
        "CategoryName": "Presidential",
        "CategoryOrder": "4",
        "GroupName": "NULL",
        "GroupOrder": "999",
        "PRINTORDER": "8",
        "BOLD": "0",
        "PERIODTYPE": "Y",
        "ROOMTYPE": "P",
        "Checkbox": "0",
        "TotAccess": "0",
        "Link": "0"
    }
]