//MEMBER
export const GET_MEMBRT = 'GET_MEMBER';

export const GUEST_INFORMATION = 'GUEST_INFORMATION';
export const SALE_CAPTURE = 'SALE_CAPTURE';
export const BENEFITS = 'BENEFITS';
export const PACKAGE_ACCESS = 'PACKAGE_ACCESS';
export const VAT_RATE = 'VAT_RATE';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';

export const ADD_NOTE = 'ADD_NOTE';

//coOwners
export const POST_COOWNER = 'POST_COOWNER';
export const POST_COOWNER_SUCCESS = 'POST_COOWNER_SUCCESS';
export const GET_COOWNER = 'GET_COOWNER';
export const GET_COOWNER_SUCCESS = 'GET_COOWNER_SUCCESS';
export const GET_COOWNER_DELETE = 'GET_COOWNER_DELETE';
export const COOWNER_DELETE_SUCCESS = 'COOWNER_DELETE_SUCCESS';
export const SELECT_COOWNER_EDIT = 'SELECT_COOWNER_EDIT';
export const COOWNER_EDIT_SUCCESS = 'COOWNER_EDIT_SUCCESS';

//Social Media
export const GET_SOCIALMEDIA = 'GET_SOCIALMEDIA';
export const GET_SOCIALMEDIA_SUCCESS = 'GET_SOCIALMEDIA_SUCCESS';
export const GET_USER_SOCIAL_MEDIA = 'GET_USER_SOCIAL_MEDIA';


//GEO CLEAN
export const DELETE_GEO = 'DELETE_GEO';

//Email
export const ADD_EMAIL = 'ADD_EMAIL';
export const DELETE_EMAIL = 'DELETE_EMAIL';
export const DELETE_EMAIL_CONFIRM = 'DELETE_EMAIL_CONFIRM';
export const ADD_EMAIL_CONFIRM = 'ADD_EMAIL_CONFIRM';
export const GET_EMAIL = 'GET_EMAIL';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
export const POST_EMAIL = 'POST_EMAIL';
export const POST_EMAIL_SUCCESS = 'POST_EMAIL_SUCCESS';
export const EMAIL_EDIT_SUCCESS = 'EMAIL_EDIT_SUCCESS';
export const GET_EMAIL_DELETE = 'GET_EMAIL_DELETE';
export const EMAIL_DELETE_SUCCESS = 'EMAIL_DELETE_SUCCESS';
export const ADD_EMAIL_TABLE = 'ADD_EMAIL_TABLE';
//Beneficiaries

export const POST_BENEFICIARIES = 'POST_BENEFICIARIES';
export const POST_BENEFICIARIES_SUCCESS = 'POST_BENEFICIARIES_SUCCESS';
export const GET_BENEFICIARIES = 'GET_BENEFICIARIES';
export const GET_BENEFICIARIES_SUCCESS = 'GET_BENEFICIARIES_SUCCESS'
export const GET_BENEFICIARIES_DELETE = 'GET_BENEFICIARIES_DELETE';
export const BENEFICIARIES_DELETE_SUCCESS = 'BENEFICIARIES_DELETE_SUCCESS';
export const SELECT_BENEFICIARIES_EDIT = 'SELECT_BENEFICIARIES_EDIT';
export const BENEFICIARIES_EDIT_SUCCESS = 'BENEFICIARIES_EDIT_SUCCESS';

//Buscador GeographicLocation
export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE';
export const SELECT_TABLE_GEO = 'SELECT_TABLE_GEO';
export const GET_GEOLOCA = 'GET_GEOLOCA'


//Tabla SocialMedia
export const ADD_SOCIAL_MEDIA = 'ADD_SOCIAL_MEDIA';
export const DELETE_SOCIAL_MEDIA = 'DELETE_SOCIAL_MEDIA';
export const DELETE_SOCIAL_MEDIA_USER = 'DELETE_SOCIAL_MEDIA_USER';

//Member by Application
export const GET_MEMBERBYAPPLICATION = 'GET_MEMBERBYAPPLICATION';
export const GET_MEMBERBYAPPLICATION_SUCCESS = 'GET_MEMBERBYAPPLICATION_SUCCESS';
export const GET_MEMBERBYAPPLICATION_FAILURE = 'GET_MEMBERBYAPPLICATION_FAILURE';

//GuesId
export const GET_GUESTID = 'GET_GUESTID';
export const GET_GUESTID_SUCCESS = 'GET_GUESTID_SUCCESS';
export const GET_GUESTID_FAILURE = 'GET_GUESTID_FAILURE';

//ProfileId
export const GET_PROFILEID =  'GET_PROFILEID';
export const GET_PROFILEID_SUCCESS = 'GET_PROFILEID_SUCCESS';
export const GET_PROFILEID_FAILURE = 'GET_PROFILEID_FAILURE';

//MemberProfile
export const GET_MEMBERPROFILE =  'GET_MEMBERPROFILE';
export const GET_MEMBERPROFILE_SUCCESS = 'GET_MEMBERPROFILE_SUCCESS';
export const GET_MEMBERPROFILE_FAILURE = 'GET_MEMBERPROFILE_FAILURE';

//CreditCards
export const POST_CREDITCARD = 'POST_CREDITCARD';
export const POST_CREDITCARD_SUCCESS = 'POST_CREDITCARD_SUCCESS';
export const GET_CREDITCARD = 'GET_CREDITCARD';
export const GET_CREDITCARD_SUCCESS = 'GET_CREDITCARD_SUCCESS';
export const GET_CREDITCARD_DELETE = 'GET_CREDITCARD_DELETE';
export const CREDITCARD_DELETE_SUCCESS = 'CREDITCARD_DELETE_SUCCESS';
export const SELECT_CREDITCARD_EDIT = 'SELECT_CREDITCARD_EDIT';
export const CREDITCARD_EDIT_SUCCESS = 'CREDITCARD_EDIT_SUCCESS';

